languageCode = 'en'
title = 'thedmdim'
theme = 'book'

[Params]
logo = 'thedmdim'
metrika = 90000000

[Params.contacts]
github = "github.com/thedmdim"


[markup.highlight]
anchorLineNos = false
codeFences = true
lineNos = false
lineNumbersInTable = true