baseURL = 'thedmdim.github.io'
languageCode = 'en'
title = 'thedmdim'
theme = 'book'

[Params]
logo = 'thedmdim'
metrika = 90000000

[markup.highlight]
    anchorLineNos = false
    codeFences = true
    lineNos = false
    lineNumbersInTable = true